language: node_js
node_js:
  - '11'
script: 'true'
deploy:
  provider: heroku
  api_key:
    secure: ovKGWlzW4KLUC/PazvyAgnxnU7OBhFiHgOM6XkHOUFiaEujtQzZBDyRAD4K+mxK+xTSH9Q5a4NYy9p0gAfVkshHJqJYo+kxAOqGVYn3OsUanPEQvDurIeunE8X5Phn5rqnykLm3X8pv6xT8652XCtgiyeS5FkWcPuLtgVO4Zt9wfbIrQRJuZZ+UW3ROctbMsWQ1wQfxZgYX6UDQ2EgpStO4yiEQJiZmtZT2gWLBsMmnHMC8TMXwMNyxVoRb8qEpfmckrrlnDDLkGsMw2LIhqBa04Foas2F0PAWZXb2r54mxcxFUaTUhhdyCtkNzpdA3sEyLgjARMnMp+4zaGbhN8CK07iF7CTDnRNqCWHos24fpWCDEPFeUTaHZ3NEDhyNdJ/MlC4Xx8ELMoiMssvldOHh8Z8EWmOTKfdIP47ja30PkXyvzLsfIPo3EhJi64ESOBisZg4uC6miz0/jvbx8fGrDbSii5Fn5BiV3LzQVgXxZRf3zmt5j2m0MGUvJS85tiJ6/booCtzrMe1B2+6rNo07wqQrAjZ7ZPMTNPKAzy7Hg5qm/KHuBv79Ial4N6EwUVb8wcUwejdmcWMpOSylcPbLcLL3mqCkgZciGlhmPeZ+DZ1gTV3FqhOEyGm/N+7HVcYrrGETj1BeFYJfQDbmuk4HYho2nk6Vvx9RzX8JofTZ0I=
  app: leenkim-wedding
